######################### DEFAULTS #########################

defaults:
    - model: encoder_head
    - optimizer: sgd
    - scheduler: plateau
    - optimizer@r_optimizer: rsgd
    - neptune_cfg: jk
    - _self_

########################### HYDRA ############################

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed

  run:
    dir: experiments/single/${now:%Y-%m-%d}/${now:%H:%M:%S}

  sweep:
    dir: experiments/multi/${hydra.job.name}/${now:%Y-%m-%d_%H:%M:%S}
    subdir: ${hydra.job.override_dirname}/seed=${seed}


####################### TRAINING PARAMS ##########################

epochs: 200
seed: 777  # seed for training the model
bs: 256  # batch size


########################## OTHER DEFINITIONS ############################

model:
    input_dim: ${..dataset_params.dim}

r_scheduler:
    name: None

metrics:
    loss: MSE
    additional: [MSE, MAPE]