epochs: 200
seed: 777

dataset_params:
    n_samples: 1.0e+5  # it will be divided in 70:20:10 ratio
    dim: 2
    eps: 1.0e-2
    bs: 256

model:
    name: EuclideanFFNModel
    input_dim: 2
    hidden_dims: [128, 256, 256, 128, 64, 64]
    activations: relu
    batch_norm: False
    skips: False

optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9

scheduler:
    name: ReduceLROnPlateau
    factor: 0.75
    verbose: True
    eps: 1.0e-7

metrics:
    loss: MSE
    additional: [MAPE]

# fill to log run to neptune
# neptune:
#    project: xxxxxx
#    api_token: xxxxxx