epochs: 200

dataset_params:
    n_samples: 1.0e+5  # it will be divided in 70:20:10 ratio
    dim: 2
    eps: 1.0e-2
    bs: 256

model:
    name: EuclideanFFNModel
    input_dim: 2
    hidden_dims: [128, 256, 256, 128, 64, 64]
    activations: relu

optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9

scheduler:
    name: ReduceLROnPlateau
    factor: 0.9
    verbose: True
    eps: 1.0e-7

metrics:
    loss: MSE
    additional: [MAPE]

neptune:
    project: jkociniak/hyperbolic-dist-pred
    api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIxMmVmNjk0Yi1hMmZjLTQ3NmYtODBkZi1mZmM2NDMwNTk1ZTcifQ==